AWSTemplateFormatVersion: 2010-09-09
Description: 'Citrix Server VDA'

Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: Network Configuration
        Parameters:
          - PrivateVDASubnet1
          - PrivateVDASubnet2
      - Label:
          default: Amazon EC2 Configuration
        Parameters:
          - KeyPairName
          - VDAInstanceType
          - VDAWindowsServerVersion          
      - Label:
          default: Active Directory Configuration
        Parameters:
          - ADServer1PrivateIP
          - ADServer2PrivateIP
          - DomainDNSName
          - DomainNetBIOSName
          - DomainAdminPassword
          - DomainAdminUser
      - Label:
          default: AWS Quick Start Configuration
        Parameters:
          - QSS3BucketName
          - QSS3KeyPrefix
    ParameterLabels:
      ADServer1PrivateIP:
        default: Domain Controller 1 Private IP Address
      ADServer2PrivateIP:
        default: Domain Controller 2 Private IP Address      
      DomainAdminPassword:
        default: Domain Admin Password
      DomainAdminUser:
        default: Domain Admin User Name
      DomainDNSName:
        default: Domain DNS Name
      DomainNetBIOSName:
        default: Domain NetBIOS Name
      KeyPairName:
        default: Key Pair Name
      PrivateVDASubnet1:
        default: Private Citrix VDA Subnet 1 ID
      PrivateVDASubnet2:
        default: Private Citrix VDA Subnet 2 ID
      QSS3BucketName:
        default: Quick Start S3 Bucket Name
      QSS3KeyPrefix:
        default: Quick Start S3 Key Prefix
      VDAInstallationFileName:
        default: Citrix VDA Install Media
      VDAInstanceType:
        default: Citrix Server VDA Instance Type
      VDAWindowsServerVersion:
        default: Windows Server Version for Citrix Server VDA        

Parameters:
  ADServer1PrivateIP:
    Type: String
  ADServer2PrivateIP:
    Type: String    
  DomainDNSName:
    AllowedPattern: '[a-zA-Z0-9\-]+\..+'
    Default: example.com
    Description: >-
      Fully qualified domain name (FQDN) of the forest root domain e.g.
      example.com
    MaxLength: '255'
    MinLength: '2'
    Type: String
  DomainNetBIOSName:
    AllowedPattern: '[a-zA-Z0-9\-]+'
    Default: example
    Description: >-
      NetBIOS name of the domain (up to 15 characters) for users of earlier
      versions of Windows e.g. EXAMPLE
    MaxLength: '15'
    MinLength: '1'
    Type: String
  DomainAdminPassword:
    Type: String
  DomainAdminUser:
    AllowedPattern: '[a-zA-Z0-9]*'
    Default: admin
    Description: >-
      User name for the account that will be added as Domain Administrator. This
      is separate from the default "Administrator" account. Note: Use admin if using managed AD.
    MaxLength: '25'
    MinLength: '5'
    Type: String
  KeyPairName:
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
    Description: >-
      Name of an existing EC2 KeyPair used to get the Administrator password for
      the instance
    Type: 'AWS::EC2::KeyPair::KeyName'
  PrivateVDASubnet1:
    Type: 'AWS::EC2::Subnet::Id'
    MinLength: '1'
  PrivateVDASubnet2:
    Type: 'AWS::EC2::Subnet::Id'
    MinLength: '1'
  QSS3BucketName:
    AllowedPattern: '^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$'
    ConstraintDescription: >-
      Quick Start bucket name can include numbers, lowercase letters, uppercase
      letters, and hyphens (-). It cannot start or end with a hyphen (-).
    Default: aws-quickstart
    Description: >-
      S3 bucket name for the Quick Start assets. This bucket name can include
      numbers, lowercase letters, uppercase letters, and hyphens (-), but should
      not start or end with a hyphen. You can specify your own bucket if you
      copy all of the assets and submodules into it, if you want to override the
      Quick Start behavior for your specific implementation.
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: '^[0-9a-zA-Z-/]*$'
    ConstraintDescription: >-
      Quick Start key prefix can include numbers, lowercase letters, uppercase
      letters, hyphens (-), and forward slash (/).
    Default: quickstart-citrix-xenappxendesktop/
    Description: >-
      S3 key prefix for the Quick Start assets. Quick Start key prefix can
      include numbers, lowercase letters, uppercase letters, hyphens (-), and
      forward slash (/).
    Type: String  
  VDAInstallationFileName:
    Type: String
    Default: VDAServerSetup_7.17.exe
  VDAInstanceType:
    Default: t2.medium
    Type: String
  VDASecurityGroup:
    Type: 'AWS::EC2::SecurityGroup::Id'
  VDAWindowsServerVersion:
    Description: Version of preferred Windows Server for the Citrix Cloud Connectors.
    Type: String
    Default: WS2016FULLBASE
    AllowedValues:
      - WS2012R2
      - WS2016FULLBASE    

Mappings:
  AWSAMIRegionMap:
    AMI:
      WS2012R2: Windows_Server-2012-R2_RTM-English-64Bit-Base-2018.03.24
      WS2016FULLBASE: Windows_Server-2016-English-Full-Base-2018.03.24
    ap-northeast-1:
      WS2012R2: ami-3badff5d
      WS2016FULLBASE: ami-6ccf9d0a
    ap-northeast-2:
      WS2012R2: ami-dde34cb3
      WS2016FULLBASE: ami-ece04f82
    ap-northeast-3:
      WS2012R2: ami-00757d27a0476b33c
      WS2016FULLBASE: ami-0c56d476b019fcd31
    ap-south-1:
      WS2012R2: ami-d8b9e2b7
      WS2016FULLBASE: ami-cabde6a5
    ap-southeast-1:
      WS2012R2: ami-169fc06a
      WS2016FULLBASE: ami-b294cbce
    ap-southeast-2:
      WS2012R2: ami-e68f4384
      WS2016FULLBASE: ami-058a4667
    ca-central-1:
      WS2012R2: ami-56fd7b32
      WS2016FULLBASE: ami-d5fd7bb1
    eu-central-1:
      WS2012R2: ami-0bdc8fe0
      WS2016FULLBASE: ami-29c192c2
    eu-west-1:
      WS2012R2: ami-e9104190
      WS2016FULLBASE: ami-2316475a
    eu-west-2:
      WS2012R2: ami-19688e7e
      WS2016FULLBASE: ami-9c6b8dfb
    eu-west-3:
      WS2012R2: ami-802492fd
      WS2016FULLBASE: ami-7225930f
    sa-east-1:
      WS2012R2: ami-6ed38702
      WS2016FULLBASE: ami-9ede8af2
    us-east-1:
      WS2012R2: ami-eb1ecd96
      WS2016FULLBASE: ami-ed14c790
    us-east-2:
      WS2012R2: ami-2f16274a
      WS2016FULLBASE: ami-8e1627eb
    us-west-1:
      WS2012R2: ami-4e07112e
      WS2016FULLBASE: ami-6d04120d
    us-west-2:
      WS2012R2: ami-651f811d
      WS2016FULLBASE: ami-8b1886f3


Resources:
  VDA:
    Type: 'AWS::EC2::Instance'
    Metadata:
      'AWS::CloudFormation::Authentication':
        S3AccessCreds:
          type: S3
          roleName: !Ref VDARole
          buckets:
            - !Ref QSS3BucketName
      'AWS::CloudFormation::Init':
        configSets:
          config:
            - "CFNsetup"
            - "QuickStartSetup"
            - "rename"
            - "domainjoin"          
            - "installVDA"
            - "finalize"
        CFNsetup:
          files:
            'c:\cfn\cfn-hup.conf':
              content: !Join 
                - ''
                - - |
                    [main]
                  - stack=
                  - !Ref 'AWS::StackId'
                  - |+

                  - region=
                  - !Ref 'AWS::Region'
                  - |+

            'c:\cfn\hooks.d\cfn-auto-reloader.conf':
              content: !Join 
                - ''
                - - |
                    [cfn-auto-reloader-hook]
                  - |
                    triggers=post.update
                  - >
                    path=Resources.VDA.Metadata.AWS::CloudFormation::Init
                  - 'action=cfn-init.exe -v -s '
                  - !Ref 'AWS::StackId'
                  - ' -r VDA'
                  - ' --region '
                  - !Ref 'AWS::Region'
                  - |+

          commands:
            a-set-execution-policy:
              command: powershell.exe -command Set-ExecutionPolicy RemoteSigned 
              waitAfterCompletion: '0'
        QuickStartSetup:
          files:
            'C:\cfn\scripts\Unzip-Archive.ps1':
              source: !Sub https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}submodules/quickstart-microsoft-utilities/scripts/Unzip-Archive.ps1
              authentication: S3AccessCreds 
            'C:\cfn\modules\AWSQuickStart.zip':
              source: !Sub https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}submodules/quickstart-microsoft-utilities/modules/AWSQuickStart.zip
              authentication: S3AccessCreds           
          commands:
            a-unpack-quickstart-module:
              command: >-
                powershell.exe -Command C:\cfn\scripts\Unzip-Archive.ps1 -Source
                C:\cfn\modules\AWSQuickStart.zip -Destination
                C:\Windows\system32\WindowsPowerShell\v1.0\Modules\
              waitAfterCompletion: '0'
        rename:  
          commands:
            a-execute-powershell-script-RenameComputer:  
              command: !Sub | 
                powershell.exe -Command Rename-Computer -NewName VDA -Restart
              waitAfterCompletion: 'forever'
        domainjoin:  
          files:
            'c:\cfn\scripts\Set-Dns.ps1':
              source: !Sub 'https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}submodules/quickstart-microsoft-utilities/scripts/Set-Dns.ps1'
              authentication: S3AccessCreds              
            'c:\cfn\scripts\Join-Domain.ps1':
              source: !Sub 'https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}submodules/quickstart-microsoft-utilities/scripts/Join-Domain.ps1'
              authentication: S3AccessCreds  
          commands:
            a-set-dns:
              command: !Sub |
                powershell.exe c:\cfn\scripts\Set-Dns.ps1 ${ADServer1PrivateIP} ${ADServer2PrivateIP}
              waitAfterCompletion: '30'
            b-join-domain:
              command: !Sub |
                powershell.exe c:\cfn\scripts\Join-Domain.ps1 ${DomainDNSName} ${DomainNetBIOSName}\${DomainAdminUser} ${DomainAdminPassword}
              waitAfterCompletion: 'forever'
        installVDA:
          files:
            'c:\cfn\scripts\VDAServerSetup_7_15.exe':
              source: !Sub 'https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}scripts/VDAServerSetup_7_15.exe'
              authentication: S3AccessCreds
            'C:\cfn\scripts\InstallVcRedistandWindowsServerFeatures.ps1':
              source: !Sub 'https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}scripts/InstallVcRedistandWindowsServerFeatures.ps1'
              authentication: S3AccessCreds
            'c:\cfn\scripts\InstallServerOSVirtualDeliveryAgent.ps1':
              source: !Sub 'https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}scripts/InstallServerOSVirtualDeliveryAgent.ps1'
              authentication: S3AccessCreds 
            'c:\cfn\scripts\DisableIEESC.ps1':
              source: !Sub 'https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}scripts/DisableIEESC.ps1'
              authentication: S3AccessCreds
          commands:
            1-DisableIEESC:
              command: powershell C:\cfn\scripts\DisableIEESC.ps1
              waitAfterCompletion: '0'
            2-execute-powershell-script-AInstallVcRedistandWindowsServerFeatures:
              command: powershell.exe -ExecutionPolicy Unrestricted C:\cfn\scripts\InstallVcRedistandWindowsServerFeatures.ps1
              waitAfterCompletion: '300'
            3-execute-powershell-script-InstallXDVDA:
              command: powershell.exe -ExecutionPolicy Unrestricted C:\cfn\scripts\InstallServerOSVirtualDeliveryAgent.ps1
              IgnoreErrors: 'true'
              waitAfterCompletion: '300'
            4-reboot:
              command: powershell.exe -Command Restart-Computer -Force
              waitAfterCompletion: forever
        finalize:  
          commands:
            z-signal-success:
              command: !Sub |
                cfn-signal.exe -e 0 "${VDAWaitHandle}"
          services:
            windows:
              cfn-hup:
                enabled: 'true'
                ensureRunning: 'true'
                files:
                  - 'c:\cfn\cfn-hup.conf'
                  - 'c:\cfn\hooks.d\cfn-auto-reloader.conf'        
    Properties:
      IamInstanceProfile: !Ref VDAProfile
      InstanceType: !Ref VDAInstanceType
      ImageId: !FindInMap [ AWSAMIRegionMap, !Ref "AWS::Region", !Ref VDAWindowsServerVersion ]
      SecurityGroupIds:
        - !Ref VDASecurityGroup
      KeyName: !Ref KeyPairName
      SubnetId: !Ref PrivateVDASubnet1
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-VDA'
        - Key: App
          Value: Citrix
      UserData: !Base64 
        'Fn::Join':
          - ''
          - - |
              <script>
            - 'cfn-init.exe -v -s '
            - !Ref 'AWS::StackId'
            - ' -r VDA'
            - ' --region '
            - !Ref 'AWS::Region'
            - ' --configsets config'
            - |+
            - </script>

  VDAWaitHandle:
    Type: 'AWS::CloudFormation::WaitConditionHandle'
  VDAWaitCondition:
    Type: 'AWS::CloudFormation::WaitCondition'
    DependsOn: VDA
    Properties:
      Handle: !Ref VDAWaitHandle
      Timeout: '3600'


  VDARole:
    Type: 'AWS::IAM::Role'
    Properties:
      Policies:
        - PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                  - 's3:GetObject'
                Resource: !Sub 'arn:aws:s3:::${QSS3BucketName}/${QSS3KeyPrefix}*'
                Effect: Allow
          PolicyName: aws-quick-start-s3-policy
      Path: /
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Principal:
              Service:
                - ec2.amazonaws.com
            Effect: Allow
        Version: 2012-10-17

  VDAProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Roles:
        - !Ref VDARole
      Path: /


Outputs:
  VDA:
    Description: VDA EC2 instance
    Value: !Ref VDA
  VDARole:
    Value: !Ref VDARole