AWSTemplateFormatVersion: 2010-09-09
Description: 'VPC Security Groups'
Parameters:
  VPCID:
    Type: 'AWS::EC2::VPC::Id'

Resources:
  CCSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group which allows access to the Cloud Connectors
      VpcId: !Ref VPCID
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          IpProtocol: -1
          FromPort: -1
          ToPort: -1
      Tags:
      - Key: Name
        Value: CC-sg
      - Key: App
        Value: Citrix
  VDASecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group which allows access to the VDA Workers
      VpcId: !Ref VPCID
      SecurityGroupIngress:
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
      Tags:
      - Key: Name
        Value: vda-sg
      - Key: App
        Value: Citrix
Outputs:
  CCSecurityGroup:
    Value: !Ref CCSecurityGroup
  VDASecurityGroup:
    Value: !Ref VDASecurityGroup
